version: 2
references:
  default-job: &default-job
    working_directory: ~/alpine-pkg-py-pandas
jobs:
  build:
    <<: *default-job
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Docker volumes
          command: |
            docker create --name input --volume /home/builder/package alpine:3.8 /bin/true
            docker create --name output --volume /packages alpine:3.8 /bin/true
            docker cp . input:/home/builder/package/
      - run:
          name: Build packages
          command: |
            docker run --env RSA_PRIVATE_KEY="$RSA_PRIVATE_KEY" --env RSA_PRIVATE_KEY_NAME="sgerrand.rsa" \
                       --volumes-from input --volumes-from output sgerrand/alpine-abuild:3.8
      - run:
          name: Test installing packages
          command: |
            wget https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
            docker cp sgerrand.rsa.pub output:/packages/
            docker run --volumes-from output alpine:3.8 sh -c "cp /packages/sgerrand.rsa.pub /etc/apk/keys/ && apk add --no-progress --update-cache --upgrade /packages/builder/x86_64/*.apk"
      - run:
          name: Extract packages
          command: |
            mkdir -p packages
            docker cp output:/packages/builder packages/
      - run:
          name: Remove Docker volumes
          command: |
            docker rm input
            docker rm output
          when: always
      - store_artifacts:
          destination: pkgs
          path: packages
      - store_artifacts:
          destination: pkgs
          path: packages
      - persist_to_workspace:
          root: .
          paths:
            - packages
  release-master:
    <<: *default-job
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease -delete unreleased packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease unreleased packages/builder/x86_64
  release-tag:
    <<: *default-job
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages/builder/x86_64
workflows:
  version: 2
  build-test-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release-master:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - release-tag:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+){1,2}(\-r\d+)?$/
